services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: "poetry install"
    startCommand: "poetry run gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DEBUG
        value: "False"
      - fromDotEnv: true
